# Generated by Django 5.2 on 2026-03-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('recognizing', 'Recognizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('segments_total', models.IntegerField(default=0)),
                ('segments_done', models.IntegerField(default=0)),
                ('tracks_found', models.IntegerField(default=0)),
                ('tracklist', models.JSONField(blank=True, default=list)),
                ('description_tracks', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
