# Generated by Django 5.2 on 2026-03-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0002_add_raw_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizejob',
            name='engine',
            field=models.CharField(blank=True, default='shazam', max_length=20),
        ),
    ]
