# Generated by Django 5.2 on 2026-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0003_add_engine_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizejob',
            name='acrcloud_calls',
            field=models.IntegerField(default=0),
        ),
    ]
