# Generated by Django 5.2 on 2026-07-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traxdb', '0002_scrapedfolder_scrapedtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedfolder',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
