# Generated by Django 5.2 on 2026-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traxdb', '0003_alter_scrapedfolder_download_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dirs', models.JSONField(default=list, help_text='YYYY-MM-DD folders present on the Mac')),
                ('reported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mac inventory',
            },
        ),
        migrations.AddField(
            model_name='scrapedfolder',
            name='claim_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scrapedfolder',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
