# Generated by Django 5.2 on 2026-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traxdb', '0004_macinventory_scrapedfolder_claim_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macinventory',
            name='file_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='macinventory',
            name='total_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
