# Generated by Django 5.2 on 2026-03-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soulseek', '0003_backfill_queue_items'),
        ('wanted', '0004_add_playlist_name_to_importoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=1000)),
                ('current_path', models.CharField(max_length=1000)),
                ('final_filename', models.CharField(blank=True, max_length=1000)),
                ('artist', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('album', models.CharField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('catalog_number', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('track_number', models.CharField(blank=True, max_length=10)),
                ('has_artwork', models.BooleanField(default=False)),
                ('stage', models.CharField(choices=[('downloaded', 'Downloaded'), ('tagging', 'Tagging'), ('tagged', 'Tagged'), ('renaming', 'Renaming'), ('renamed', 'Renamed'), ('ready', 'Ready'), ('failed', 'Failed')], default='downloaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata_source', models.CharField(blank=True, choices=[('file', 'File Tags'), ('discogs', 'Discogs'), ('musicbrainz', 'MusicBrainz'), ('manual', 'Manual')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('download', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_items', to='soulseek.download')),
                ('wanted_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_items', to='wanted.wanteditem')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
