# Generated by Django 5.2 on 2026-02-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WantedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('blog', 'Blog'), ('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('youtube', 'YouTube'), ('telegram', 'Telegram')], default='manual', max_length=50)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WantedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, help_text='e.g. "heard in Feb mix at 23:15"')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('identified', 'Identified'), ('searching', 'Searching'), ('found', 'Found'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('tagged', 'Tagged'), ('organized', 'Organized'), ('not_found', 'Not Found'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('identified_via', models.CharField(blank=True, choices=[('manual', 'Manual'), ('acoustid', 'AcoustID'), ('shazam', 'Shazam')], max_length=20, null=True)),
                ('acoustid_fingerprint', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('search_count', models.IntegerField(default=0)),
                ('last_searched', models.DateTimeField(blank=True, null=True)),
                ('best_match_score', models.FloatField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='wanted.wantedsource')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
