# Generated by Django 5.2 on 2026-02-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanteditem',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='e.g. WARP123', max_length=100),
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='release_name',
            field=models.CharField(blank=True, help_text='Album or EP name', max_length=500),
        ),
    ]
