# Generated by Django 5.2 on 2026-02-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0002_wanteditem_catalog_number_wanteditem_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsource',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('blog', 'Blog'), ('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discogs', 'Discogs')], default='manual', max_length=50),
        ),
        migrations.CreateModel(
            name='ImportOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('youtube', 'YouTube'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('discogs', 'Discogs')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('previewing', 'Previewing'), ('importing', 'Importing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('preview_data', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('total_found', models.IntegerField(default=0)),
                ('duplicates_found', models.IntegerField(default=0)),
                ('items_imported', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_operations', to='wanted.wantedsource')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
