# Generated by Django 5.2 on 2026-03-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0003_alter_wantedsource_source_type_importoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='importoperation',
            name='playlist_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
