# Generated by Django 5.2 on 2026-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0004_add_playlist_name_to_importoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsource',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('blog', 'Blog'), ('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discogs', 'Discogs'), ('bandcamp', 'Bandcamp'), ('dig', 'Dig')], default='manual', max_length=50),
        ),
    ]
