# Generated by Django 5.2 on 2026-04-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hash', models.CharField(db_index=True, max_length=64)),
                ('method', models.CharField(choices=[('gemini', 'Gemini Vision'), ('vision_ocr', 'Google Vision OCR'), ('universal', 'Universal CLIP search'), ('manual', 'Manual artist+album entry')], default='gemini', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('artist_guess', models.CharField(blank=True, max_length=500)),
                ('album_guess', models.CharField(blank=True, max_length=500)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IdentifiedRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500)),
                ('album', models.CharField(max_length=500)),
                ('release_date', models.CharField(blank=True, max_length=50)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('cover_image_url', models.CharField(blank=True, max_length=2000)),
                ('discogs_url', models.CharField(blank=True, max_length=2000)),
                ('spotify_url', models.CharField(blank=True, max_length=2000)),
                ('youtube_url', models.CharField(blank=True, max_length=2000)),
                ('bandcamp_url', models.CharField(blank=True, max_length=2000)),
                ('tracklist', models.JSONField(blank=True, default=list)),
                ('market_stats', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='cratemate.albumidentification')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('sources_used', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='cratemate.albumidentification')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='cratemate.identifiedrelease')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
