# Generated by Django 5.2 on 2026-02-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('preferred_formats', models.JSONField(default=list, help_text='Ordered list: ["flac", "wav", "aiff", "mp3"]')),
                ('min_bitrate', models.IntegerField(default=256, help_text='Minimum kbps for lossy')),
                ('max_file_size_mb', models.IntegerField(default=200)),
                ('min_file_size_mb', models.IntegerField(default=2)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('bit_depth', models.IntegerField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('length_seconds', models.IntegerField(blank=True, null=True)),
                ('match_score', models.FloatField(default=0)),
                ('artist_score', models.FloatField(default=0)),
                ('title_score', models.FloatField(default=0)),
                ('upload_speed', models.IntegerField(blank=True, null=True)),
                ('queue_length', models.IntegerField(blank=True, null=True)),
                ('free_upload_slots', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wanted_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='wanted.wanteditem')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=1000)),
                ('local_path', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('slskd_id', models.CharField(blank=True, help_text='slskd transfer ID', max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wanted_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='wanted.wanteditem')),
                ('search_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soulseek.searchresult')),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
