# Generated by Django 5.2 on 2026-02-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulseek', '0001_initial'),
        ('wanted', '0002_wanteditem_catalog_number_wanteditem_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='wanted_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_results', to='wanted.wanteditem'),
        ),
        migrations.CreateModel(
            name='SearchQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('release_name', models.CharField(blank=True, max_length=500)),
                ('catalog_number', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('raw_query', models.CharField(blank=True, help_text='Free-text search query', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching'), ('found', 'Found'), ('not_found', 'Not Found'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('search_count', models.IntegerField(default=0)),
                ('last_searched', models.DateTimeField(blank=True, null=True)),
                ('best_match_score', models.FloatField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wanted_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='wanted.wanteditem')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddField(
            model_name='download',
            name='queue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='soulseek.searchqueueitem'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='queue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='soulseek.searchqueueitem'),
        ),
    ]
