# Generated by Django 5.2 on 2026-04-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulseek', '0003_backfill_queue_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
